source="CMakeFiles/SimdSse2.dir/Users/frankw/c_apps/Simd/src/Simd"
dest="/Users/frankw/golang/src/github.com/fwessels/go-cv-simd"

c2goasm -a -s -c -f "$source/SimdSse2Reorder.cpp.s"                 "$dest/SimdSse2Reorder_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2MedianFilter.cpp.s"            "$dest/SimdSse2MedianFilter_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2GaussianBlur3x3.cpp.s"         "$dest/SimdSse2GaussianBlur3x3_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2BgraToGray.cpp.s"              "$dest/SimdSse2BgraToGray_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2MeanFilter3x3.cpp.s"           "$dest/SimdSse2MeanFilter3x3_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Fill.cpp.s"                    "$dest/SimdSse2Fill_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Laplace.cpp.s"                 "$dest/SimdSse2Laplace_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2GrayToBgra.cpp.s"              "$dest/SimdSse2GrayToBgra_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2DeinterleaveUv.cpp.s"          "$dest/SimdSse2DeinterleaveUv_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Int16ToGray.cpp.s"             "$dest/SimdSse2Int16ToGray_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Binarization.cpp.s"            "$dest/SimdSse2Binarization_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2BgraToYuv.cpp.s"               "$dest/SimdSse2BgraToYuv_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2AlphaBlending.cpp.s"           "$dest/SimdSse2AlphaBlending_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2ReduceGray2x2.cpp.s"           "$dest/SimdSse2ReduceGray2x2_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2ReduceGray3x3.cpp.s"           "$dest/SimdSse2ReduceGray3x3_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2ReduceGray4x4.cpp.s"           "$dest/SimdSse2ReduceGray4x4_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2AbsGradientSaturatedSum.cpp.s" "$dest/SimdSse2AbsGradientSaturatedSum_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2SquaredDifferenceSum.cpp.s"    "$dest/SimdSse2SquaredDifferenceSum_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2AbsDifferenceSum.cpp.s"        "$dest/SimdSse2AbsDifferenceSum_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2AddFeatureDifference.cpp.s"    "$dest/SimdSse2AddFeatureDifference_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Background.cpp.s"              "$dest/SimdSse2Background_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Segmentation.cpp.s"            "$dest/SimdSse2Segmentation_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Sobel.cpp.s"                   "$dest/SimdSse2Sobel_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Conditional.cpp.s"             "$dest/SimdSse2Conditional_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Operation.cpp.s"               "$dest/SimdSse2Operation_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2StretchGray2x2.cpp.s"          "$dest/SimdSse2StretchGray2x2_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2YuvToBgra.cpp.s"               "$dest/SimdSse2YuvToBgra_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2Texture.cpp.s"                 "$dest/SimdSse2Texture_amd64.s"
c2goasm -a -s -c -f "$source/SimdSse2BgrToBgra.cpp.s"               "$dest/SimdSse2BgrToBgra_amd64.s"
